from pydoc import cli
import streamlit as st
import pandas as pd
import numpy as np
import meilisearch
import csv
import streamlit.components.v1.components as components
_my_component = components.declare_component(
    "app",
    url="http://192.168.1.2:3000"
)
#client = meilisearch.Client('http://127.0.0.1:7700', 'masterKey')


@st.cache
def loadCountries():
    df = pd.read_csv('./countries.csv', skipinitialspace=True)
    df['longitude'] = df['longitude'].astype(float)
    df['latitude'] = df['latitude'].astype(float)
    return df


countries = loadCountries()

syntax_map = {
    "sativa": "percent_sativa",
    "indica": "percent_indica",
    "ruderalis": "percent_ruderalis",
    "afghanica": "percent_afghanica"
}
'''
client.index('strains').update_filterable_attributes([
    "percent_sativa",
    "percent_indica",
    "percent_ruderalis",
    "percent_afghanica"
])
'''


search = st.text_input("Search For Anything", '')

col1, col2 = st.columns(2)

with col1:
    sativa = st.slider(
        label="percent_sativa",
        value=(0, 100))
    indica = st.slider(
        label="percent_indica",
        value=(0, 100))

with col2:
    ruderalis = st.slider(
        label="percent_ruderalis",
        value=(0, 100))
    afghanica = st.slider(
        label="percent_afghanica",
        value=(0, 100))


filter = {"sativa": sativa, "indica": indica,
          "ruderalis": ruderalis, "afghanica": afghanica}


def format(filter, search):
    filt = {"filter": " AND ".join([str(syntax_map[f] + " >" +
                                        ("= 0" if filter[f][0] == 0 else " " + str(filter[f][0])) +
                                        " AND " + syntax_map[f] + " < " +
                                        str(filter[f][1])) for f in filter])}
    return (search, filt)


s = format(filter, search)
#results = client.index('strains').search(s[0], s[1])
results = [
        {
            "id": 1,
            "name": 303,
            "description": "303 has a sweet, pleasant flavor with a piney, spicy aroma. Very intense, mind-lifting high. It can cause heart-racing and anxiety attacks for users not used to strong landrace sativa strains. Very long lasting effects. It's a cross of early 1970's landrace PNG Gold seeds and various Hawaiian/Fuji strains.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": 138,
            "created_at": "2010-07-26 17:44:38.437581",
            "updated_at": "2014-08-15 15:41:36.02176",
            "percent_sativa": 90,
            "percent_indica": 10,
            "breeder_id": "",
            "lineage": [
                "Papua New Guinea Gold",
                " Hawaiian",
                " Fuji"
            ],
            "seed_company": "Spice Brothers",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": 16,
            "height_growth": 8,
            "climate_preferred": "OUTDOOR",
            "flowering_period": 8,
            "euphoric_duration": 6,
            "seed_company_id": 123,
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": "",
            "estimated_yield": "",
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "",
            "od_estimated_yield": "",
            "cbd_content": ""
        },
        {
            "id": 10,
            "name": "AK-47",
            "description": "Dense, trichome-laden buds release a spicy, woodsy smell and a sweet, floral taste. The high comes quickly and is alert and cerebral. Very enjoyable. Goes well with music or social occasions.\\n\\n\\n\\nColumbian, Mexican, Thai & Afghani \\n\\n\\n\\nFlowering Time Indoor: 50 - 69 days (~60 days) Yield / Quantity Indoor: The crop of this strain is great. General Impression Indoor: is all together extremely good and very recommendable. Harvest Time Outdoor: Middle of October +/- 1 Week in climates. Strength / Lasting Effect: The weed is very strong and long lasting. Yield / Quantity Outdoor: The crop of this strain is slightly above average. General Impression Outdoor: is all together extraordinary and quite recommendable. \\n\\n\\n\\nGenetics: Columbian, Mexican, Thai & Afghani Harvest Date Outdoor: middle - end of OctoberIndoor clone grow time: 5 - 10 daysIndoor flowering time: 53 - 63 daysIndoor yield: 350 - 500 g/m\\u00b2This easy to grow plant is one of the most popular. It is of medium height and produces good yields quite quickly. Extremely STRONG odor and smoke. The name was given not out of any idea of violence, but more in association with the one hit wonder that the smoke is. Quality without compromise makes AK suitable for commercial grows or home use. These plants have a short flowering period for a sativa, producing compact, not too leafy buds that gleam with a coat of resin crystals.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": 33,
            "created_at": "2010-07-26 17:44:38.629511",
            "updated_at": "2014-09-07 21:52:33.15279",
            "percent_sativa": 65,
            "percent_indica": 35,
            "breeder_id": "",
            "lineage": [
                "Colombian",
                "Mexican",
                "Thai",
                "Afghani"
            ],
            "seed_company": "Serious Seeds",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": 20,
            "height_growth": "",
            "climate_preferred": "",
            "flowering_period": 9,
            "euphoric_duration": 2,
            "seed_company_id": 63,
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": 10,
            "estimated_yield": "",
            "landrace": "FALSE",
            "creation_year": 1992,
            "country_of_origin": "Netherlands",
            "od_estimated_yield": "",
            "cbd_content": ""
        },
        {
            "id": 100,
            "name": "Blue Cheese",
            "description": "The flavor is dank and woodsy with an undercurrent of blueberry fruit.  The high is very pleasant and dreamy. Relaxing, indica dominant hybrid. THC at 20%. Easy to grow. Nice yield. Short stocky plant.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": 255,
            "created_at": "2010-07-26 17:44:39.980404",
            "updated_at": "2014-08-14 22:15:34.993686",
            "percent_sativa": 25,
            "percent_indica": 75,
            "breeder_id": "",
            "lineage": [
                "Big Buddha Cheese",
                "Blueberry"
            ],
            "seed_company": "Big Buddha Seeds",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": 20,
            "height_growth": "",
            "climate_preferred": "",
            "flowering_period": 9,
            "euphoric_duration": "",
            "seed_company_id": 5,
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": 10,
            "estimated_yield": 35,
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "United Kingdom",
            "od_estimated_yield": "",
            "cbd_content": 1
        },
        {
            "id": 1004,
            "name": "Maui",
            "description": "",
            "price_per_gram": 12,
            "enabled": "TRUE",
            "image_id": 838,
            "created_at": "2010-10-29 20:43:54.033324",
            "updated_at": "2011-12-23 00:32:09.27007",
            "percent_sativa": 80,
            "percent_indica": 20,
            "breeder_id": "",
            "lineage": [
                ""
            ],
            "seed_company": "",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": "",
            "height_growth": "",
            "climate_preferred": "",
            "flowering_period": "",
            "euphoric_duration": "",
            "seed_company_id": "",
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": "",
            "estimated_yield": "",
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "",
            "od_estimated_yield": "",
            "cbd_content": ""
        },
        {
            "id": 1011,
            "name": "Big Bud",
            "description": "Sensi Seed's latest incarnation of Big Bud has more potency, huge yields, and a sweet, spicy taste. The high is mellow and long-lasting with a relaxing body stone.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": 490,
            "created_at": "2010-10-29 20:47:50.300369",
            "updated_at": "2014-08-13 16:51:17.861167",
            "percent_sativa": 30,
            "percent_indica": 70,
            "breeder_id": "",
            "lineage": [
                "SA a",
                "Big Bud",
                "Skunk 18.5Afghani"
            ],
            "seed_company": "Sensi Seed Bank",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": 16,
            "height_growth": 4,
            "climate_preferred": "INDOOR",
            "flowering_period": 8,
            "euphoric_duration": 2,
            "seed_company_id": 62,
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": 9,
            "estimated_yield": 5,
            "landrace": "FALSE",
            "creation_year": 1988,
            "country_of_origin": "Netherlands",
            "od_estimated_yield": "",
            "cbd_content": ""
        },
        {
            "id": 1024,
            "name": "707 Headband",
            "description": "Originally from the Humbolt area of California, the effect of this plant is very, very expansive. Has an earthy hash-like taste to it. The aroma offers a fresh, citrusy smell and the flowers appear as light, green, dense, frosty buds. Frequently golden haired. Nice Sativa.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": 740,
            "created_at": "2010-10-29 20:54:41.234874",
            "updated_at": "2014-08-15 15:53:17.778742",
            "percent_sativa": 80,
            "percent_indica": 20,
            "breeder_id": "",
            "lineage": [
                "Master Kush",
                "OG Kush",
                "Sour Deisel"
            ],
            "seed_company": "",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": 12,
            "height_growth": "",
            "climate_preferred": "OUTDOOR",
            "flowering_period": 8,
            "euphoric_duration": 3,
            "seed_company_id": "",
            "od_flowering_period": 9,
            "od_height_growth": "",
            "od_flowering_month": "",
            "estimated_yield": "",
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "United States",
            "od_estimated_yield": "",
            "cbd_content": 1
        },
        {
            "id": 1028,
            "name": "Pineapple",
            "description": "Fat Pineapple buds have the aroma of pineapple and fuel. This limited release of only 450 seeds has an indica buzz with a punch.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": 805,
            "created_at": "2010-10-29 20:56:56.992969",
            "updated_at": "2011-06-27 20:55:38.188748",
            "percent_sativa": 40,
            "percent_indica": 60,
            "breeder_id": "",
            "lineage": [
                "ERSBEd Rosenthal Super Bud",
                " F2 ",
                "feminized"
            ],
            "seed_company": "CH9 Female Seeds",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": "",
            "height_growth": "",
            "climate_preferred": "",
            "flowering_period": 8,
            "euphoric_duration": "",
            "seed_company_id": 12,
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": "",
            "estimated_yield": 3,
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "United Kingdom",
            "od_estimated_yield": 16,
            "cbd_content": ""
        },
        {
            "id": 103,
            "name": "Blue God",
            "description": "Blue God is a very strong, indica with a deep berry taste.  Originally a blend of Blueberry and God Bud, it is especially suitable for relief of insomnia, chronic pain and nausea. Extremely stationary and relaxing. Can be grown indoors or out. Best grown multi branch outdoors. Flowers in approximately 8 weeks. Very attractive plant.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": 593,
            "created_at": "2010-07-26 17:44:40.011169",
            "updated_at": "2014-08-14 22:46:10.768505",
            "percent_sativa": 10,
            "percent_indica": 90,
            "breeder_id": "",
            "lineage": [
                "God Bud",
                "Blueberry"
            ],
            "seed_company": "Jordan of the Islands",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": "",
            "height_growth": 4,
            "climate_preferred": "",
            "flowering_period": 8,
            "euphoric_duration": 2,
            "seed_company_id": 118,
            "od_flowering_period": "",
            "od_height_growth": 12,
            "od_flowering_month": "",
            "estimated_yield": 8,
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "Canada",
            "od_estimated_yield": 16,
            "cbd_content": ""
        },
        {
            "id": 1036,
            "name": "Querkle",
            "description": "The taste of purple grapes and berries introduces an indica head high that is relaxing and mellow, good for evening use or moderate outdoor activities.  Tinctures helpful for insomnia or pain.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": 455,
            "created_at": "2010-10-29 21:03:34.875142",
            "updated_at": "2011-01-06 20:27:26.111504",
            "percent_sativa": 20,
            "percent_indica": 80,
            "breeder_id": "",
            "lineage": [
                "Purple Urkle",
                "Space Queen"
            ],
            "seed_company": "TGA Seeds",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": 20,
            "height_growth": "",
            "climate_preferred": "",
            "flowering_period": 10,
            "euphoric_duration": 2,
            "seed_company_id": 68,
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": 10,
            "estimated_yield": 4,
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "United States",
            "od_estimated_yield": "",
            "cbd_content": ""
        },
        {
            "id": 1039,
            "name": "Purple Wreck",
            "description": "Purple Urkel x Train Wreck! This West Coast hybrid produces dense buds with a sweet, fruity aroma and an upbeat high. Should be good for depression, anxiety, and pain relief.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": 716,
            "created_at": "2010-10-29 21:05:02.56976",
            "updated_at": "2011-05-03 22:39:53.434945",
            "percent_sativa": 40,
            "percent_indica": 60,
            "breeder_id": "",
            "lineage": [
                "Purple Urkel",
                "Train Wreck"
            ],
            "seed_company": "Reserva Privada Seeds",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": "",
            "height_growth": "",
            "climate_preferred": "",
            "flowering_period": 9,
            "euphoric_duration": "",
            "seed_company_id": 52,
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": "",
            "estimated_yield": "",
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "United States",
            "od_estimated_yield": "",
            "cbd_content": ""
        },
        {
            "id": 1041,
            "name": "Sour Kush",
            "description": "See listing for Headband, aka Sour Kush. The percentage of indica is listed as higher in Sour Kush. Sour Kush has a sour fuel smell and taste, and a long-lasting high, and not heavy or sleepy. This is good for day use, and is also helpful for anxiety.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": 721,
            "created_at": "2010-10-29 21:05:58.977747",
            "updated_at": "2011-05-04 21:11:36.604196",
            "percent_sativa": 30,
            "percent_indica": 70,
            "breeder_id": "",
            "lineage": [
                "Sour Diesel",
                "OG Kush reversed"
            ],
            "seed_company": "Reserva Privada Seeds",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": "",
            "height_growth": "",
            "climate_preferred": "",
            "flowering_period": 10,
            "euphoric_duration": "",
            "seed_company_id": 52,
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": "",
            "estimated_yield": "",
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "United States",
            "od_estimated_yield": "",
            "cbd_content": ""
        },
        {
            "id": 1048,
            "name": "Big Wreck",
            "description": "Big Wreck crashes indica and sativa traits into one big indica dominant hybrid.  A clean floral, woodsy scent leads to pungent, heavy smoke that tastes of flowers and hash.  The high is strong with nice head and body effects. Good for watching a movie or playing computer games.  This strain has medicinal value, including depression, chronic pain and insomnia. CBD at 0.23%.",
            "price_per_gram": 10,
            "enabled": "TRUE",
            "image_id": 846,
            "created_at": "2010-10-29 21:09:54.648661",
            "updated_at": "2014-09-03 13:52:53.751401",
            "percent_sativa": 30,
            "percent_indica": 70,
            "breeder_id": 3,
            "lineage": [
                "Big Bud",
                "Trainwreck"
            ],
            "seed_company": "",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": 22,
            "height_growth": "",
            "climate_preferred": "",
            "flowering_period": 8,
            "euphoric_duration": 3,
            "seed_company_id": 215,
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": "",
            "estimated_yield": "",
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "United States",
            "od_estimated_yield": "",
            "cbd_content": ""
        },
        {
            "id": 105,
            "name": "Blue Grape #1",
            "description": "The sticky, crystalline buds of Blue Grape #1 offer an indica high that is both alert and energizing. Very nice indica-dominant hybrid. Excellent sativa effects. Smells like blueberries and grapefruit. Also good for pain management.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": 594,
            "created_at": "2010-07-26 17:44:40.036062",
            "updated_at": "2014-08-14 22:55:55.412585",
            "percent_sativa": 30,
            "percent_indica": 70,
            "breeder_id": "",
            "lineage": [
                "Grapefruit",
                "Blueberry"
            ],
            "seed_company": "Electric Seed Company",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": "",
            "height_growth": "",
            "climate_preferred": "",
            "flowering_period": 8,
            "euphoric_duration": 2,
            "seed_company_id": 189,
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": 9,
            "estimated_yield": 3,
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "Canada",
            "od_estimated_yield": 10,
            "cbd_content": ""
        },
        {
            "id": 1050,
            "name": "Tangerine",
            "description": "A tangerine bouquet and fruit flavors of tangerine, mango and pineapple add distinction to this indica dominant strain. The potent high is more indica with some sativa influences.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": "",
            "created_at": "2010-10-29 21:10:46.726474",
            "updated_at": "2011-06-28 22:50:03.362775",
            "percent_sativa": 40,
            "percent_indica": 60,
            "breeder_id": "",
            "lineage": [
                "CH9 Aroma",
                "CH9 Aroma"
            ],
            "seed_company": "CH9 Female Seeds",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": "",
            "height_growth": "",
            "climate_preferred": "",
            "flowering_period": 8,
            "euphoric_duration": "",
            "seed_company_id": 12,
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": "",
            "estimated_yield": 3,
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "United Kingdom",
            "od_estimated_yield": 13,
            "cbd_content": ""
        },
        {
            "id": 1051,
            "name": "Black Diamond Kush",
            "description": "Delicious Indica dominant hybrid from California. Lovely orange haired plant with gorgeous purple hues. Uplifting, energetic high. Euphoric. Gives way to a body high quickly. An indica connoisseurs delight. Hard to find (except in CA dispensaries) but well worth it if you do. Premium bud. Sometimes called Black Diamond Kush OG or simply Black Diamond.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": "",
            "created_at": "2010-10-29 21:11:13.609616",
            "updated_at": "2014-09-27 22:35:26.260772",
            "percent_sativa": 10,
            "percent_indica": 90,
            "breeder_id": "",
            "lineage": [
                "Blackberry",
                "Diamond OG"
            ],
            "seed_company": "",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": 14,
            "height_growth": "",
            "climate_preferred": "",
            "flowering_period": "",
            "euphoric_duration": "",
            "seed_company_id": "",
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": "",
            "estimated_yield": "",
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "",
            "od_estimated_yield": "",
            "cbd_content": ""
        },
        {
            "id": 1054,
            "name": "Jilly Bean",
            "description": "Ripe fruit candy?  That's Jilly Bean, with solid buds heavy with resin.  Slow to come on, she provides relaxation to body and mind.  This is mellow daytime smoke, good for chronic pain and depression.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": 650,
            "created_at": "2010-10-29 21:12:35.135967",
            "updated_at": "2011-04-13 20:33:26.448398",
            "percent_sativa": 30,
            "percent_indica": 70,
            "breeder_id": "",
            "lineage": [
                "Orange Velvet",
                "Space Queen"
            ],
            "seed_company": "TGA Seeds",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": 12,
            "height_growth": 4,
            "climate_preferred": "",
            "flowering_period": 8,
            "euphoric_duration": "",
            "seed_company_id": 68,
            "od_flowering_period": "",
            "od_height_growth": "",
            "od_flowering_month": 9,
            "estimated_yield": 4,
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "United Kingdom",
            "od_estimated_yield": "",
            "cbd_content": ""
        },
        {
            "id": 1063,
            "name": "Alaskan Thunder Fuck",
            "description": "Classic strain from 1970's Alaska. Known also as Matanuska Thunder. Commonly refers to any seed from the Matanuska Valley. Many seeds are sold as Alaskan Thunder Fuck with indica dominant characteristics but original seeds are sativa dominant and are from a cool dry environment. Uplifting energetic effects give way to a sedating body high. Light and dark green bud with orange hairs. Not recommended for operating heavy machinery.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": "",
            "created_at": "2010-10-29 21:20:15.899386",
            "updated_at": "2014-09-17 18:38:34.138762",
            "percent_sativa": 60,
            "percent_indica": 40,
            "breeder_id": 3,
            "lineage": [
                "Afghani",
                "Northern California"
            ],
            "seed_company": "",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": 14,
            "height_growth": 2,
            "climate_preferred": "",
            "flowering_period": 11,
            "euphoric_duration": 4,
            "seed_company_id": "",
            "od_flowering_period": 11,
            "od_height_growth": 2,
            "od_flowering_month": 10,
            "estimated_yield": 30,
            "landrace": "FALSE",
            "creation_year": 1975,
            "country_of_origin": "United States",
            "od_estimated_yield": 38,
            "cbd_content": 1
        },
        {
            "id": 107,
            "name": "Blue Hen II",
            "description": "Nice hybrid Courtesy of Blue Grass Seeds this second incarnation of Blue Hen features more sativa characteristics. Nice fruity smell. Nice purple hued nugs. Very pleasing to the eye. Limited supply these days. Please email with any supply info.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": "",
            "created_at": "2010-07-26 17:44:40.067255",
            "updated_at": "2014-09-28 23:24:37.15414",
            "percent_sativa": 70,
            "percent_indica": 30,
            "breeder_id": 29,
            "lineage": [
                "DP-Blueberry",
                "Super Silver Haze -GH"
            ],
            "seed_company": "Blue Grass",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": "",
            "height_growth": "",
            "climate_preferred": "",
            "flowering_period": "",
            "euphoric_duration": "",
            "seed_company_id": "",
            "od_flowering_period": "",
            "od_height_growth": 5,
            "od_flowering_month": "",
            "estimated_yield": 4,
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "",
            "od_estimated_yield": "",
            "cbd_content": ""
        },
        {
            "id": 1070,
            "name": "Amnesia",
            "description": "Warning: morning indulgence will lead to day long amnesia. This famous sativa dominant strain frequently appears in various aliases depending upon the breeder. Very pleasant, creative, euphoric high. High THC content, mild CBD. Occasionally appears as Amnesia Haze. Listed here is the strictly 'Amnesia' strain offered by Hy-Pro.",
            "price_per_gram": 0,
            "enabled": "TRUE",
            "image_id": "",
            "created_at": "2010-10-29 21:23:39.944495",
            "updated_at": "2014-09-17 21:53:22.858411",
            "percent_sativa": 60,
            "percent_indica": 40,
            "breeder_id": 7,
            "lineage": [
                "Amnesia", "Neville's Haze"
            ],
            "seed_company": "Hy-Pro Seeds",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": "",
            "height_growth": 3,
            "climate_preferred": "",
            "flowering_period": 8,
            "euphoric_duration": 3,
            "seed_company_id": 34,
            "od_flowering_period": 8,
            "od_height_growth": 4,
            "od_flowering_month": 10,
            "estimated_yield": "",
            "landrace": "FALSE",
            "creation_year": "",
            "country_of_origin": "",
            "od_estimated_yield": "",
            "cbd_content": ""
        },
        {
            "id": 1071,
            "name": "Afghani",
            "description": "Named after its historical land source, this pleasant dense indica is a historical favorite with connoisseurs everywhere. It boasts a pleasant earth based aroma and is also a favorite among breeders for its genetic qualities. Users enjoy a floating, body high that is both restorative and euphoric. A mild pain reliever, it also alleviates occasional insomnia.",
            "price_per_gram": 12,
            "enabled": "TRUE",
            "image_id": "",
            "created_at": "2010-10-29 21:24:17.462864",
            "updated_at": "2014-08-12 18:42:57.227947",
            "percent_sativa": 5,
            "percent_indica": 95,
            "breeder_id": "",
            "lineage": [
                "Afghanistan"
            ],
            "seed_company": "Mary Janes Garden",
            "percent_ruderalis": 0,
            "percent_afghanica": 0,
            "thc_content": 14,
            "height_growth": 1,
            "climate_preferred": "OUTDOOR",
            "flowering_period": 8,
            "euphoric_duration": 6,
            "seed_company_id": "",
            "od_flowering_period": 8,
            "od_height_growth": 1,
            "od_flowering_month": 10,
            "estimated_yield": 15,
            "landrace": "TRUE",
            "creation_year": "",
            "country_of_origin": "Afghanistan",
            "od_estimated_yield": 17,
            "cbd_content": 2
        }
    ]

st.metric(label="Number of Strains", value=1)#'''results['nbHits']''')

# st.write(results)

_my_component()
